// <auto-generated />
using System;
using Lab.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab.Persistence.Migrations
{
    [DbContext(typeof(PrimaryDbContext))]
    [Migration("20260331122803_InitialPrimarySchema")]
    partial class InitialPrimarySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Lab.Persistence.Entities.Cart", b =>
                {
                    b.Property<string>("CartId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cart_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("CartId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_carts_user_status");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("Lab.Persistence.Entities.CartItem", b =>
                {
                    b.Property<string>("CartItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cart_item_id");

                    b.Property<DateTimeOffset>("AddedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_utc");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cart_id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int>("UnitPriceCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_price_cents");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_cart_items_cart_product");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("Lab.Persistence.Entities.InventoryRecord", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("available_quantity");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reserved_quantity");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("ProductId");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("Lab.Persistence.Entities.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("CartId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cart_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("submitted_utc");

                    b.Property<int>("TotalPriceCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_price_cents");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId", "CreatedUtc")
                        .HasDatabaseName("ix_orders_user_created");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Lab.Persistence.Entities.OrderItem", b =>
                {
                    b.Property<string>("OrderItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_item_id");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int>("UnitPriceCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_price_cents");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .HasDatabaseName("ix_order_items_order_product");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Lab.Persistence.Entities.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_id");

                    b.Property<int>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<DateTimeOffset>("AttemptedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("attempted_utc");

                    b.Property<DateTimeOffset?>("ConfirmedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_utc");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_reference");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payments_order");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Lab.Persistence.Entities.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_cents");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("ProductId");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_products_category");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Lab.Persistence.Entities.QueueJob", b =>
                {
                    b.Property<string>("QueueJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("queue_job_id");

                    b.Property<DateTimeOffset>("AvailableUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("available_utc");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_utc");

                    b.Property<DateTimeOffset>("EnqueuedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("enqueued_utc");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("job_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("lease_expires_utc");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("lease_owner");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("QueueJobId");

                    b.HasIndex("Status", "AvailableUtc")
                        .HasDatabaseName("ix_queue_jobs_status_available");

                    b.ToTable("queue_jobs", (string)null);
                });

            modelBuilder.Entity("Lab.Persistence.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Lab.Persistence.Entities.Cart", b =>
                {
                    b.HasOne("Lab.Persistence.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lab.Persistence.Entities.CartItem", b =>
                {
                    b.HasOne("Lab.Persistence.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab.Persistence.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lab.Persistence.Entities.InventoryRecord", b =>
                {
                    b.HasOne("Lab.Persistence.Entities.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("Lab.Persistence.Entities.InventoryRecord", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lab.Persistence.Entities.Order", b =>
                {
                    b.HasOne("Lab.Persistence.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lab.Persistence.Entities.OrderItem", b =>
                {
                    b.HasOne("Lab.Persistence.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab.Persistence.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lab.Persistence.Entities.Payment", b =>
                {
                    b.HasOne("Lab.Persistence.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Lab.Persistence.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Lab.Persistence.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Lab.Persistence.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Inventory");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Lab.Persistence.Entities.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
